### ISSUE TITLE
Refine Camera

### ISSUE THREAD

**Issue by vitorverasm** [vitorverasm/squadra#8]
## Description

As mentioned in #7 we have a Camera component that is in raw form. So the task is to refine it and approximate as much as possible to the [prototyped](https://github.com/vitorverasm/squadra/wiki/prototypes) version.

## Tasks
- [x] Update UI
- [x] TagSelector component
- [x] Handle `unauthorized` state(permissions)
- [x] Show indicator while saving photo
- [x] Update/write/rewrite tests
